version: "3"
services:
  consul:
    image: "consul:1.15.4"
    ports:
      - "8500:8500"
  mysql:
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo_proto
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
    #   interval: 15s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 1m
  redis:
    image: "redis:latest"
    ports:
      - 6379:6379
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./deploy/config/alert_rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  loki:
    image: grafana/loki:2.9.2
    volumes:
      - ./deploy/config/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./deploy/config/promtail.yml:/etc/promtail/config.yml
      - ./app/frontend/log:/logs/frontend
    command: -config.file=/etc/promtail/config.yml
  # frontend:
  #   # build:
  #   #   context: .
  #   #   dockerfile: ./deploy/Dockerfile.frontend
  #   image: "gomall-frontend:latest"
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://120.0.0.1:4317
  #     - OTEL_EXPORTER_OTLP_INSECURE=true
  #     - SESSION_SECRET=ASDQWEZXTT
  #     - GO_ENV=dev
  #   depends_on:
  #     - consul
  #     - redis
  #   volumes:
  #     - ./app/frontend/conf/dev:/opt/gomall/frontend/conf/dev
  # product:
  #   # build:
  #   #   context: .
  #   #   dockerfile: ./deploy/Dockerfile.svc
  #   #   args:
  #   #     - SVC=product
  #   image: "gomall-product:latest"
  #   environment:
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=root
  #     - MYSQL_HOST=mysql
  #     - GO_ENV=dev
  #   depends_on:
  #     consul:
  #       condition: service_started
  #     mysql:
  #       condition: service_healthy
  #   volumes:
  #     - ./app/product/conf/dev:/opt/gomall/product/conf/dev
  # user:
  #   # build:
  #   #   context: .
  #   #   dockerfile: ./deploy/Dockerfile.svc
  #   #   args:
  #   #     - SVC=user
  #   image: "gomall-user:latest"
  #   environment:
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=root
  #     - MYSQL_HOST=mysql
  #     - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
  #     - OTEL_EXPORTER_OTLP_INSECURE=true
  #     - GO_ENV=dev
  #   depends_on:
  #     consul:
  #       condition: service_started
  #     mysql:
  #       condition: service_healthy
  #   volumes:
  #     - ./app/user/conf/dev:/opt/gomall/user/conf/dev
  # cart:
  #   # build:
  #   #   context: .
  #   #   dockerfile: ./deploy/Dockerfile.svc
  #   #   args:
  #   #     - SVC=cart
  #   image: "gomall-cart:latest"
  #   environment:
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=root
  #     - MYSQL_HOST=mysql
  #     - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
  #     - OTEL_EXPORTER_OTLP_INSECURE=true
  #     - GO_ENV=dev
  #   depends_on:
  #     consul:
  #       condition: service_started
  #     mysql:
  #       condition: service_healthy
  #   volumes:
  #     - ./app/cart/conf/dev:/opt/gomall/cart/conf/dev
  # checkout:
  #   # build:
  #   #   context: .
  #   #   dockerfile: ./deploy/Dockerfile.svc
  #   #   args:
  #   #     - SVC=checkout
  #   image: "gomall-checkout:latest"
  #   environment:
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=root
  #     - MYSQL_HOST=mysql
  #     - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
  #     - OTEL_EXPORTER_OTLP_INSECURE=true
  #     - GO_ENV=dev
  #   depends_on:
  #     consul:
  #       condition: service_started
  #     mysql:
  #       condition: service_healthy
  #   volumes:
  #     - ./app/checkout/conf/dev:/opt/gomall/checkout/conf/dev
  # email:
  #   # build:
  #   #   context: .
  #   #   dockerfile: ./deploy/Dockerfile.svc
  #   #   args:
  #   #     - SVC=email
  #   image: "gomall-email:latest"
  #   environment:
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=root
  #     - MYSQL_HOST=mysql
  #     - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
  #     - OTEL_EXPORTER_OTLP_INSECURE=true
  #     - GO_ENV=dev
  #   depends_on:
  #     consul:
  #       condition: service_started
  #     mysql:
  #       condition: service_healthy
  #   volumes:
  #     - ./app/email/conf/dev:/opt/gomall/email/conf/dev
  # order:
  #   # build:
  #   #   context: .
  #   #   dockerfile: ./deploy/Dockerfile.svc
  #   #   args:
  #   #     - SVC=order
  #   image: "gomall-order:latest"
  #   environment:
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=root
  #     - MYSQL_HOST=mysql
  #     - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
  #     - OTEL_EXPORTER_OTLP_INSECURE=true
  #     - GO_ENV=dev
  #   depends_on:
  #     consul:
  #       condition: service_started
  #     mysql:
  #       condition: service_healthy
  #   volumes:
  #     - ./app/order/conf/dev:/opt/gomall/order/conf/dev
  # payment:
  #   # build:
  #   #   context: .
  #   #   dockerfile: ./deploy/Dockerfile.svc
  #   #   args:
  #   #     - SVC=payment
  #   image: "gomall-payment:latest"
  #   environment:
  #     - MYSQL_USER=root
  #     - MYSQL_PASSWORD=root
  #     - MYSQL_HOST=mysql
  #     - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=jaeger-all-in-one:4317
  #     - OTEL_EXPORTER_OTLP_INSECURE=true
  #     - GO_ENV=dev
  #   depends_on:
  #     consul:
  #       condition: service_started
  #     mysql:
  #       condition: service_healthy
  #   volumes:
  #     - ./app/payment/conf/dev:/opt/gomall/payment/conf/dev
