global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "consul"
    consul_sd_configs:
      - server: consul:8500
        services:
          - prometheus
    relabel_configs:
      - source_labels: [ __meta_consul_tags ]
        action: replace
        target_label: service
        regex: ".*service:(.*?),.*"
        replacement: "$1"

      - source_labels: [ __meta_consul_service_id ]
        target_label: __metrics_path__
        replacement: /metrics
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://localhost:8080 # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9115  # The blackbox exporter's real hostname:port. (host.docker.internal for Docker Mac or Windows)
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - host.docker.internal:9093
rule_files:
  - "alert_rules.yml"